name: Create Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: The sem-ver of this release
        required: true
        type: string
      includeAndroidApk:
        description: Create an android jar
        type: boolean
        default: true
      includeAndroidAab:
        description: Create an android app bundle
        type: boolean
        default: true
      includeDesktopDeb:
        description: Create a debian bundle
        type: boolean
        default: true
      includeDesktopMsi:
        description: Create a microsoft installer
        type: boolean
        default: true
      includeDesktopDmg:
        description: Create a mac dmg package
        type: boolean
        default: true
      includeDesktopExe:
        description: Create a exe file
        type: boolean
        default: true
      includeWebDist:
        description: Create a static web distribution
        type: boolean
        default: true

env:
  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
  SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
  SIGNING_STORE_BASE_64: ${{ secrets.SIGNING_STORE_BASE_64 }}

  APK_OUTPUT_DIR: "./composeApp/build/outputs/apk/release/"
  AAB_OUTPUT_DIR: "./composeApp/build/outputs/bundle/release/"

jobs:
  buildAndroid:
    name: Create Android Packages

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Create keystore file
        run: |
          echo ${SIGNING_STORE_BASE_64} > release-keystore.jks.base64.txt
          cat release-keystore.jks.base64.txt | base64 -d > release-keystore.jks

      - name: Create APK
        if: ${{ inputs.includeAndroidApk }}
        run: |
          ./gradlew assembleRelease
          mv "${APK_OUTPUT_DIR}composeApp-release.apk" "${APK_OUTPUT_DIR}mol-${{ inputs.releaseVersion }}.apk"

      - name: Create AAB
        if: ${{ inputs.includeAndroidAab }}
        run: |
          ./gradlew bundleRelease
          mv "${AAB_OUTPUT_DIR}composeApp-release.aab" "${AAB_OUTPUT_DIR}mol-${{ inputs.releaseVersion }}.aab"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mol-android-${{ inputs.releaseVersion }}.apk
          path: ${{ env.APK_OUTPUT_DIR }}composeApp-release.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mol-android-${{ inputs.releaseVersion }}.aab
          path: ${{ env.AAB_OUTPUT_DIR }}composeApp-release.aab

  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.releaseVersion }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: my-own-lawbook/mplat-client
          body: <Create changelog>
          body_path: ./changelogs/${{ inputs.releaseVersion }}.md
          name: ${{ inputs.releaseVersion }}
          tag_name: ${{ inputs.releaseVersion }}
          files: |
            ${{ env.APK_OUTPUT_DIR }}mol-${{ inputs.releaseVersion }}.apk
            ${{ env.AAB_OUTPUT_DIR }}mol-${{ inputs.releaseVersion }}.aab
