name: Test and Lint

on:
  pull_request_target:
    branches:
      - develop
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Execute Gradle check

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Execute gradle check
        run: ./gradlew check
  sonar:
    # SonarQube scan is executed only on branches from this organization to prevent leaking the SONAR_TOKEN
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    name: Execute SonarQube scan

    steps:
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
